In [4]:
import pandas as pd
import seaborn as sns
import numpy as np
import os
import sys

from matplotlib import pyplot as plt
from dotenv import load_dotenv

sys.path.append("../")

from scripts.preprocessing import get_binary_column

load_dotenv()
sns.color_palette('colorblind')
plt.style.use('Solarize_Light2')

# Setting default DPI, pulling it from dotenv if it exists, setting it on 100 if not

try:
    pc_dpi = int(os.getenv('DPI'))
except TypeError:
    pc_dpi = 100
if pc_dpi is None:
    pc_dpi = 100

In [2]:
home_credit = "../data/home_credit_data_train.pkl"

df_home_credit = pd.read_pickle(filepath_or_buffer=home_credit)

In [3]:
df_home_credit.head()

,SK_ID_CURR,TARGET,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,...,PREV_PRODUCT_COMBINATION_POS household with interest_mean,PREV_PRODUCT_COMBINATION_POS household without interest_mean,PREV_PRODUCT_COMBINATION_POS industry with interest_mean,PREV_PRODUCT_COMBINATION_POS industry without interest_mean,PREV_PRODUCT_COMBINATION_POS mobile with interest_mean,PREV_PRODUCT_COMBINATION_POS mobile without interest_mean,PREV_PRODUCT_COMBINATION_POS other with interest_mean,PREV_PRODUCT_COMBINATION_POS others without interest_mean,PREV_PRODUCT_COMBINATION_nan_mean,PREV_number_applications
0,100002,0,0,0,0,202500.0,406597.5,24700.5,351000.0,0.018801,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,1.0,0.0,0.0,1.0
1,100003,1,0,1,0,270000.0,1293502.5,35698.5,1129500.0,0.003541,...,0.333333,0.0,0.333333,0.0,0.000000,0.0,0.0,0.0,0.0,3.0
2,100004,1,1,0,0,67500.0,135000.0,6750.0,135000.0,0.010032,...,0.000000,0.0,0.000000,0.0,0.000000,1.0,0.0,0.0,0.0,1.0
3,100006,1,0,0,0,135000.0,312682.5,29686.5,297000.0,0.008019,...,0.111111,0.0,0.111111,0.0,0.000000,0.0,0.0,0.0,0.0,9.0
4,100007,1,0,0,0,121500.0,513000.0,21865.5,513000.0,0.028663,...,0.166667,0.0,0.000000,0.0,0.166667,0.0,0.0,0.0,0.0,6.0

In [5]:
binary_cols = get_binary_column(dataframe=df_home_credit)

In [6]:
binary_cols.__len__()

176

In [7]:
df_home_credit_light = df_home_credit.drop(columns=binary_cols)

In [31]:
na_cols = df_home_credit[df_home_credit.columns[df_home_credit.isna().sum() != 0]].isna().sum()

In [41]:
na_cols.sort_values()

cnt = 0

for col, value in na_cols.items():
    if value > 50_000:
        print(col)
        cnt += 1

print(cnt)

DAYS_EMPLOYED
OWN_CAR_AGE
EXT_SOURCE_1
EXT_SOURCE_3
APARTMENTS_AVG
BASEMENTAREA_AVG
YEARS_BEGINEXPLUATATION_AVG
YEARS_BUILD_AVG
COMMONAREA_AVG
ELEVATORS_AVG
ENTRANCES_AVG
FLOORSMAX_AVG
FLOORSMIN_AVG
LANDAREA_AVG
LIVINGAPARTMENTS_AVG
LIVINGAREA_AVG
NONLIVINGAPARTMENTS_AVG
NONLIVINGAREA_AVG
APARTMENTS_MODE
BASEMENTAREA_MODE
YEARS_BEGINEXPLUATATION_MODE
YEARS_BUILD_MODE
COMMONAREA_MODE
ELEVATORS_MODE
ENTRANCES_MODE
FLOORSMAX_MODE
FLOORSMIN_MODE
LANDAREA_MODE
LIVINGAPARTMENTS_MODE
LIVINGAREA_MODE
NONLIVINGAPARTMENTS_MODE
NONLIVINGAREA_MODE
APARTMENTS_MEDI
BASEMENTAREA_MEDI
YEARS_BEGINEXPLUATATION_MEDI
YEARS_BUILD_MEDI
COMMONAREA_MEDI
ELEVATORS_MEDI
ENTRANCES_MEDI
FLOORSMAX_MEDI
FLOORSMIN_MEDI
LANDAREA_MEDI
LIVINGAPARTMENTS_MEDI
LIVINGAREA_MEDI
NONLIVINGAPARTMENTS_MEDI
NONLIVINGAREA_MEDI
TOTALAREA_MODE
DAYS_EMPLOYED_PERC
BUR_AMT_ANNUITY_max
BUR_AMT_ANNUITY_mean
BUR_AMT_CREDIT_SUM_DEBT_max
BUR_AMT_CREDIT_SUM_DEBT_mean
BUR_AMT_CREDIT_SUM_LIMIT_mean
CARD_AMT_BALANCE_mean
CARD_AMT_BALANCE_sum
CARD_AMT_CREDIT_LIMIT_ACTUAL_mean
CARD_AMT_CREDIT_LIMIT_ACTUAL_sum
CARD_AMT_DRAWINGS_ATM_CURRENT_mean
CARD_AMT_DRAWINGS_ATM_CURRENT_sum
CARD_AMT_DRAWINGS_CURRENT_mean
CARD_AMT_DRAWINGS_CURRENT_sum
CARD_AMT_DRAWINGS_OTHER_CURRENT_sum
CARD_AMT_DRAWINGS_POS_CURRENT_sum
CARD_AMT_INST_MIN_REGULARITY_mean
CARD_AMT_PAYMENT_CURRENT_mean
CARD_AMT_PAYMENT_TOTAL_CURRENT_mean
CARD_AMT_RECEIVABLE_PRINCIPAL_sum
CARD_AMT_RECIVABLE_sum
CARD_AMT_TOTAL_RECEIVABLE_sum
CARD_CNT_DRAWINGS_ATM_CURRENT_sum
CARD_CNT_DRAWINGS_CURRENT_sum
CARD_CNT_DRAWINGS_OTHER_CURRENT_sum
CARD_CNT_DRAWINGS_POS_CURRENT_sum
CARD_CNT_INSTALMENT_MATURE_CUM_sum
CARD_SK_DPD_mean
CARD_SK_DPD_max
CARD_SK_DPD_DEF_mean
CARD_SK_DPD_DEF_max
CARD_NAME_CONTRACT_STATUS_Active_mean
CARD_NAME_CONTRACT_STATUS_Approved_mean
CARD_NAME_CONTRACT_STATUS_Completed_mean
CARD_NAME_CONTRACT_STATUS_Demand_mean
CARD_NAME_CONTRACT_STATUS_Refused_mean
CARD_NAME_CONTRACT_STATUS_Sent proposal_mean
CARD_NAME_CONTRACT_STATUS_Signed_mean
CARD_NAME_CONTRACT_STATUS_nan_mean
PREV_DAYS_FIRST_DRAWING_mean
87

In [40]:
80 / df_home_credit_light.columns.__len__()

0.140597539543058

In [42]:
df_home_credit

,SK_ID_CURR,TARGET,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,...,PREV_PRODUCT_COMBINATION_POS household with interest_mean,PREV_PRODUCT_COMBINATION_POS household without interest_mean,PREV_PRODUCT_COMBINATION_POS industry with interest_mean,PREV_PRODUCT_COMBINATION_POS industry without interest_mean,PREV_PRODUCT_COMBINATION_POS mobile with interest_mean,PREV_PRODUCT_COMBINATION_POS mobile without interest_mean,PREV_PRODUCT_COMBINATION_POS other with interest_mean,PREV_PRODUCT_COMBINATION_POS others without interest_mean,PREV_PRODUCT_COMBINATION_nan_mean,PREV_number_applications
0,100002,0,0,0,0,202500.0,406597.5,24700.5,351000.0,0.018801,...,0.000000,0.0,0.000000,0.0,0.000000,0.0,1.0,0.0,0.0,1.0
1,100003,1,0,1,0,270000.0,1293502.5,35698.5,1129500.0,0.003541,...,0.333333,0.0,0.333333,0.0,0.000000,0.0,0.0,0.0,0.0,3.0
2,100004,1,1,0,0,67500.0,135000.0,6750.0,135000.0,0.010032,...,0.000000,0.0,0.000000,0.0,0.000000,1.0,0.0,0.0,0.0,1.0
3,100006,1,0,0,0,135000.0,312682.5,29686.5,297000.0,0.008019,...,0.111111,0.0,0.111111,0.0,0.000000,0.0,0.0,0.0,0.0,9.0
4,100007,1,0,0,0,121500.0,513000.0,21865.5,513000.0,0.028663,...,0.166667,0.0,0.000000,0.0,0.166667,0.0,0.0,0.0,0.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,1,0,1,0,157500.0,254700.0,27558.0,225000.0,0.032561,...,0.000000,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.0,1.0
307507,456252,1,0,0,0,72000.0,269550.0,12001.5,225000.0,0.025164,...,0.000000,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,1.0
307508,456253,1,0,0,0,153000.0,677664.0,29979.0,585000.0,0.005002,...,0.000000,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.0,2.0
307509,456254,0,0,0,0,171000.0,370107.0,20205.0,319500.0,0.005313,...,0.500000,0.0,0.000000,0.0,0.500000,0.0,0.0,0.0,0.0,2.0
307510,456255,1,0,1,0,157500.0,675000.0,49117.5,675000.0,0.046220,...,0.000000,0.0,0.125000,0.0,0.250000,0.0,0.0,0.0,0.0,8.0